[versions]
android-compileSdk = "36"
android-minSdk = "27"
android-targetSdk = "35"

agp = "8.13.1"
firebaseBom = "34.6.0"
googleServicesVersion = "4.4.4"
gradle = "8.13.1"
inAppReviewKmpGooglePlay = "3.4.3"
kmpauthGoogle = "2.3.1"
kmpnotifier = "1.6.0"
kotlin = "2.2.21"
googleServices = "4.4.4"
kotlinGradlePlugin = "2.1.0"
kotlinxSerializationJson = "1.9.0"
multiplatformSettings = "1.3.0"
permissions = "0.18.1"
richeditorCompose = "1.0.0-rc13"
secretsPlugin = "2.0.1"
baselineProfile = "1.0.0"
compose-multiplatform = "1.9.3"
androidx-lifecycle = "2.9.6"

compose = "1.9.5"
androidx-activityCompose = "1.12.0"
appcompat = "1.7.1"
material3 = "1.4.0"
constraintlayout = "1.1.1"
coreKtx = "1.17.0"
coreSplashscreen = "1.0.1"
datastorePreferences = "1.1.7"
lifecycle = "2.10.0"
lifecycleExtensions = "2.2.0"
navigationCompose = "2.9.6"
roomKtx = "2.8.4"
profileInstaller = "1.4.1"
datetime = "0.7.1"
workRuntimeKtx = "2.11.0"
accompanistPermissions = "0.36.0"
playReview = "2.0.2"
espresso = "3.7.0"
androidxJunit = "1.3.0"
mockk = "1.14.6"
uiTestManifest = "1.9.5"
junit = "4.13.2"
animatedList = "0.5.1"
googleid = "1.1.1"
firebase = "2.4.0"
playServicesAuth = "21.4.0"
playServicesAds = "24.7.0"
credentials = "1.5.0"
koin = "4.1.1"
kotlinxCoroutines = "1.10.2"
ktor = "3.3.2"
openaiBom = "4.0.1"
parceler = "1.1.13"
coil = "2.7.0"
landscapist = "2.6.1"
billingClient = "8.0.0"
vico = "2.3.6"
ycharts = "2.1.0"
serialization = "1.9.0"
jetbrainsKotlinMultiplatform = "2.2.21"
androidKotlinMultiplatformLibrary = "8.8.0-rc01"
kotlinStdlib = "2.2.21"
kotlinTest = "2.2.20"
runner = "1.7.0"
core = "1.7.0"
runtimeAndroid = "1.7.6"
runtimeJvmstubs = "1.7.6"
runtimeDesktop = "1.7.0"
firebaseAuthCommon = "9.8.0"

lexilabs-basic = "+" # gets the latest version

purchases-kmp = "2.2.10+17.19.1"
purchases-common = "13.3.0"
[libraries]
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-common = { module = "dev.gitlive:firebase-common", version.ref = "firebase" }
google-services = { module = "com.google.gms:google-services", version.ref = "googleServicesVersion" }
gradle = { module = "com.android.tools.build:gradle", version.ref = "gradle" }
in1-app-review-kmp-google-play = { module = "io.github.sergeimikhailovskii:in-app-review-kmp-google-play", version.ref = "inAppReviewKmpGooglePlay" }
kmpauth-firebase = { module = "io.github.mirzemehdi:kmpauth-firebase", version.ref = "kmpauthGoogle" }
kmpauth-google = { module = "io.github.mirzemehdi:kmpauth-google", version.ref = "kmpauthGoogle" }
kmpauth-uihelper = { module = "io.github.mirzemehdi:kmpauth-uihelper", version.ref = "kmpauthGoogle" }
kmpnotifier = { module = "io.github.mirzemehdi:kmpnotifier", version.ref = "kmpnotifier" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlinGradlePlugin" }
kotlinx-serialization-json-v180rc = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinxSerializationJson" }
ktor-client-android = { module = "io.ktor:ktor-client-android", version.ref = "ktor" }
ktor-client-content-negotiation = { module = "io.ktor:ktor-client-content-negotiation", version.ref = "ktor" }
ktor-client-darwin = { module = "io.ktor:ktor-client-darwin", version.ref = "ktor" }
ktor-serialization-kotlinx-json = { module = "io.ktor:ktor-serialization-kotlinx-json", version.ref = "ktor" }
landscapist-coil3 = { module = "com.github.skydoves:landscapist-coil3", version.ref = "landscapist" }
material3 = { module = "androidx.compose.material3:material3", version.ref = "material3" }
material3WindowSize = { module = "androidx.compose.material3:material3-window-size-class", version.ref = "material3" }
animation = { module = "androidx.compose.animation:animation", version.ref = "compose" }
composeUi = { module = "androidx.compose.ui:ui", version.ref = "compose" }
composeUiToolingPreview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
constraintLayoutCompose = { module = "androidx.constraintlayout:constraintlayout-compose", version.ref = "constraintlayout" }
coreKtx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
coreSplashscreen = { module = "androidx.core:core-splashscreen", version.ref = "coreSplashscreen" }
datastorePreferences = { module = "androidx.datastore:datastore-preferences", version.ref = "datastorePreferences" }
lifecycleExtensions = { module = "androidx.lifecycle:lifecycle-extensions", version.ref = "lifecycleExtensions" }
lifecycleRuntimeCompose = { module = "androidx.lifecycle:lifecycle-runtime-compose", version.ref = "lifecycle" }
lifecycleRuntimeKtx = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycle" }
lifecycleViewModelCompose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "lifecycle" }
lifecycleViewModelKtx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycle" }
materialIconsExtended = { module = "androidx.compose.material:material-icons-extended", version.ref = "compose" }
multiplatform-settings = { module = "com.russhwolf:multiplatform-settings", version.ref = "multiplatformSettings" }
multiplatform-settings-datastore = { module = "com.russhwolf:multiplatform-settings-datastore", version.ref = "multiplatformSettings" }
navigationCompose = { module = "androidx.navigation:navigation-compose", version.ref = "navigationCompose" }
permissions = { module = "dev.icerock.moko:permissions", version.ref = "permissions" }
permissions-compose = { module = "dev.icerock.moko:permissions-compose", version.ref = "permissions" }
richeditor-compose = { module = "com.mohamedrejeb.richeditor:richeditor-compose", version.ref = "richeditorCompose" }
roomKtx = { module = "androidx.room:room-ktx", version.ref = "roomKtx" }
profileInstaller = { module = "androidx.profileinstaller:profileinstaller", version.ref = "profileInstaller" }
datetime = { module = "org.jetbrains.kotlinx:kotlinx-datetime", version.ref = "datetime" }
workRuntimeKtx = { module = "androidx.work:work-runtime-ktx", version.ref = "workRuntimeKtx" }
accompanistPermissions = { module = "com.google.accompanist:accompanist-permissions", version.ref = "accompanistPermissions" }
playReview = { module = "com.google.android.play:review", version.ref = "playReview" }
playReviewKtx = { module = "com.google.android.play:review-ktx", version.ref = "playReview" }
espressoCore = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso" }
androidxJunit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
uiTestJunit4 = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
uiTestManifest = { module = "androidx.compose.ui:ui-test-manifest", version.ref = "uiTestManifest" }
junit = { module = "junit:junit", version.ref = "junit" }
animatedList = { module = "com.github.SmartToolFactory:Compose-AnimatedList", version.ref = "animatedList" }
googleid = { module = "com.google.android.libraries.identity.googleid:googleid", version.ref = "googleid" }
firebaseFirestore = { module = "dev.gitlive:firebase-firestore", version.ref = "firebase" }
firebaseFunctions = { module = "dev.gitlive:firebase-functions", version.ref = "firebase" }
firebaseStorage = { module = "dev.gitlive:firebase-storage", version.ref = "firebase" }
firebaseAuth = { module = "dev.gitlive:firebase-auth", version.ref = "firebase" }
firebaseAnalytics = { module = "dev.gitlive:firebase-analytics", version.ref = "firebase" }
playServicesAuth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }
playServicesAds = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
credentials = { module = "androidx.credentials:credentials", version.ref = "credentials" }
credentialsPlayServicesAuth = { module = "androidx.credentials:credentials-play-services-auth", version.ref = "credentials" }

koin-android = { module = "io.insert-koin:koin-android", version.ref = "koin" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koin" }
koin-androidx-compose = { module = "io.insert-koin:koin-androidx-compose", version.ref = "koin" }
koinComposeNavigation = { module = "io.insert-koin:koin-androidx-compose-navigation", version.ref = "koin" }
koin-compose = { module = "io.insert-koin:koin-compose", version.ref = "koin" }
koin-compose-viewmodel = { module = "io.insert-koin:koin-compose-viewmodel", version.ref = "koin" }

koinTest = { module = "io.insert-koin:koin-test", version.ref = "koin" }
koinTestJunit5 = { module = "io.insert-koin:koin-test-junit5", version.ref = "koin" }
kotlin-serialization-json = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "serialization" }


# Kotlin Coroutines
kotlinxCoroutinesAndroid = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
kotlinxCoroutinesCore = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinxCoroutinesPlayServices = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-play-services", version.ref = "kotlinxCoroutines" }

# Networking


# OpenAI
openaiClientBom = { module = "com.aallam.openai:openai-client-bom", version.ref = "openaiBom" }
openaiClient = { module = "com.aallam.openai:openai-client", version.ref = "openaiBom" }

# Other Libraries
parcelerApi = { module = "org.parceler:parceler-api", version.ref = "parceler" }
parceler = { module = "org.parceler:parceler", version.ref = "parceler" }

# Image Loading
coil = { module = "io.coil-kt:coil", version.ref = "coil" }
coilCompose = { module = "io.coil-kt:coil-compose", version.ref = "coil" }
landscapistCoil = { module = "com.github.skydoves:landscapist-coil", version.ref = "landscapist" }
landscapistPlaceholder = { module = "com.github.skydoves:landscapist-placeholder", version.ref = "landscapist" }
landscapistPalette = { module = "com.github.skydoves:landscapist-palette", version.ref = "landscapist" }
landscapistTransformation = { module = "com.github.skydoves:landscapist-transformation", version.ref = "landscapist" }

# Billing Client
billingClient = { module = "com.android.billingclient:billing", version.ref = "billingClient" }

# Chart Libraries
vico-multiplatform = { group = "com.patrykandpatrick.vico", name = "multiplatform", version.ref = "vico" }
vico-multiplatform-m3 = { group = "com.patrykandpatrick.vico", name = "multiplatform-m3", version.ref = "vico" }
ychartsDreamjournalai = { module = "co.yml:ycharts", version.ref = "ycharts" }
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlinStdlib" }
kotlin-test = { group = "org.jetbrains.kotlin", name = "kotlin-test", version.ref = "kotlinTest" }
runner = { group = "androidx.test", name = "runner", version.ref = "runner" }
core = { group = "androidx.test", name = "core", version.ref = "core" }

androidx-lifecycle-viewmodel = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-viewmodel", version.ref = "androidx-lifecycle" }
androidx-lifecycle-runtime-compose = { group = "org.jetbrains.androidx.lifecycle", name = "lifecycle-runtime-compose", version.ref = "androidx-lifecycle" }
firebase-auth-common = { group = "com.google.firebase", name = "firebase-auth-common", version.ref = "firebaseAuthCommon" }

lexilabs-basic-ads = { module = "app.lexilabs.basic:basic-ads", version.ref = "lexilabs-basic"}

purchases-core = { module = "com.revenuecat.purchases:purchases-kmp-core", version.ref = "purchases-kmp" }
# Optional: adds extension properties representing timestamps as kotlinx-datetime Instants.
purchases-datetime = { module = "com.revenuecat.purchases:purchases-kmp-datetime", version.ref = "purchases-kmp" }
# Optional: adds suspending functions that return Arrow's Either to indicate success / failure.
purchases-either = { module = "com.revenuecat.purchases:purchases-kmp-either", version.ref = "purchases-kmp" }
# Optional: adds suspending functions that return kotlin.Result to indicate success / failure.
purchases-result = { module = "com.revenuecat.purchases:purchases-kmp-result", version.ref = "purchases-kmp" }

ktor-client-okhttp = { module = "io.ktor:ktor-client-okhttp", version.ref = "ktor" }
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinSerialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "jetbrainsKotlinMultiplatform" }
composeMultiplatform = { id = "org.jetbrains.compose", version.ref = "compose-multiplatform" }
composeCompiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServices" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
androidKotlinMultiplatformLibrary = { id = "com.android.kotlin.multiplatform.library", version.ref = "agp" }
androidLint = { id = "com.android.lint", version.ref = "agp" }